package com.example.caregiverphase2.model.pojo.search_job

data class Data(
    val address: String,
    val amount: String,
    val appartment_or_unit: String,
    val bidding_end_time: Any,
    val bidding_start_time: Any,
    val care_items: List<CareItem>,
    val care_type: String,
    val check_list: List<Any>,
    val city: String,
    val country: String,
    val created_at: String,
    val deleted_at: Any,
    val description: String,
    val end_date: String,
    val end_time: String,
    val expertise: List<Any>,
    val floor_no: String,
    val id: Int,
    val lat: String,
    val long: String,
    val medical_history: List<String>,
    val other_requirements: List<Any>,
    val payment_status: Int,
    val short_address: String,
    val start_date: String,
    val start_time: String,
    val state: String,
    val status: String,
    val street: String,
    val title: String,
    val updated_at: String,
    val user_id: Int,
    val zip_code: String
)